version: "3.4"
services:
    pgAdmin:
        restart: always
        container_name: pgAdmin4
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: 1234@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
            - pgadmin:/var/lib/pgadmin
volumes:
    pgadmin: 
